# Generated by Django 4.2.1 on 2023-05-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_instacjaksiazki_wypozycza'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='gatunek',
            field=models.ManyToManyField(help_text='Gatunek tej ksiazki', to='katalog.gatunek'),
        ),
    ]
