# Generated by Django 4.2.1 on 2023-05-12 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_ksiazka_gatunek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('data_zatrudnienia', models.DateField(blank=True, null=True)),
                ('stanowisko', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='Wydawca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('miasto', models.CharField(max_length=100)),
                ('data_zalozenia', models.DateField(blank=True, null=True)),
                ('krs', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['nazwa', 'miasto'],
            },
        ),
        migrations.AddField(
            model_name='instacjaksiazki',
            name='bibliotekarz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.bibliotekarz'),
        ),
        migrations.AlterField(
            model_name='instacjaksiazki',
            name='wydawca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.wydawca'),
        ),
    ]
