# Generated by Django 4.2.1 on 2023-05-13 02:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('katalog', '0004_bibliotekarz_wydawca_instacjaksiazki_bibliotekarz_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstacjaKsiazki',
            new_name='InstancjaKsiazki',
        ),
    ]
